## Server
server:
  port: ${SERVER_PORT:9001}

## MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:twitter}?serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:passw}

ums:
  host: ${UMS_HOST:http://localhost}
  port: ${UMS_PORT:9000}
  paths:
    user: /users/user